import Link from "next/link";
import { ArrowUpRight, Bell, FileCheck2, Gauge, LayoutDashboard, LogOut, Settings, Users } from "lucide-react";
import { StatusPill } from "@/components/status-pill";

const applications = [{ id: "ETM-APP-1042", instrument: "Electronic counter scale", status: "Certified" as const, date: "28 Sep 2026" }, { id: "ETM-APP-1039", instrument: "Platform weighing scale", status: "Scheduled" as const, date: "02 Oct 2026" }, { id: "ETM-APP-1031", instrument: "Retail measure set", status: "Submitted" as const, date: "24 Sep 2026" }];

export default function DashboardPage() {
  return <div className="dashboard-shell"><aside className="sidebar"><div className="brand-mark"><span>eT</span><div><strong>eTulaMaan</strong><small>Legal Metrology</small></div></div><nav className="side-nav"><Link className="active" href="/dashboard"><LayoutDashboard size={17} /> Overview</Link><Link href="/dashboard/certificates"><FileCheck2 size={17} /> Certificates</Link><Link href="/dashboard/instruments"><Gauge size={17} /> Instruments</Link><Link href="/dashboard/notifications"><Bell size={17} /> Notifications <span className="nav-count">3</span></Link></nav><div className="side-bottom"><Link href="/dashboard/settings"><Settings size={17} /> Settings</Link><Link href="/"><LogOut size={17} /> Sign out</Link></div></aside><main className="dashboard-main"><header className="dashboard-header"><div><p className="eyebrow">Owner workspace</p><h1>Good morning, Ananya.</h1></div><div className="avatar">AS</div></header><section className="dashboard-welcome"><div><span className="welcome-label">Your compliance overview</span><h2>Keep every measure ready for trade.</h2><p>Two instruments need your attention this month.</p></div><Link className="button button-primary" href="/dashboard/apply">Add instrument <ArrowUpRight size={16} /></Link></section><section className="metric-grid"><div className="metric-card"><span>Active instruments</span><strong>12</strong><small>Across 3 locations</small></div><div className="metric-card"><span>Valid certificates</span><strong>9</strong><small className="green-text">75% in compliance</small></div><div className="metric-card"><span>Renewal due soon</span><strong>2</strong><small className="gold-text">Within 60 days</small></div></section><section className="table-section"><div className="section-heading inline"><div><p className="eyebrow">Recent activity</p><h2>Applications</h2></div><Link className="text-link" href="/dashboard/applications">View all <ArrowUpRight size={15} /></Link></div><div className="table-wrap"><table><thead><tr><th>Application</th><th>Instrument</th><th>Status</th><th>Updated</th></tr></thead><tbody>{applications.map((application) => <tr key={application.id}><td className="strong-cell">{application.id}</td><td>{application.instrument}</td><td><StatusPill status={application.status} /></td><td>{application.date}</td></tr>)}</tbody></table></div></section><div className="placeholder-banner"><Users size={18} /><span><strong>Demo workspace</strong> Seed data is marked as placeholder until connected to your organisation.</span></div></main></div>;
}
