"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, UserRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { TopBar } from "@/components/top-bar";

export default function RegisterPage() {
  const [step, setStep] = useState<1 | 2>(1);
  const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); if (step === 1) setStep(2); else { const data = new FormData(event.currentTarget); if (data.get("otp") !== "123456") { setError("Use the demo OTP 123456 to verify this account."); return; } localStorage.setItem("etulamaan_user", JSON.stringify({ name: data.get("name"), email: data.get("email"), role: "OWNER" })); window.location.href = "/dashboard"; } };
  return <div className="site-shell"><TopBar /><main className="login-layout register-layout"><section className="login-intro"><p className="eyebrow">Owner registration</p><h1>Bring your instruments into the fold.</h1><p>Create an owner account, complete the simulated e-KYC step, and start your first verification application.</p><div className="login-assurance"><CheckCircle2 size={20} /><span>Demo e-KYC OTP: 123456</span></div></section><section className="login-card"><div className="login-card-heading"><div className="feature-icon"><UserRound size={21} /></div><p className="eyebrow">Step {step} of 2</p><h2>{step === 1 ? "Create your account" : "Verify your phone"}</h2></div><form onSubmit={submit}>{step === 1 ? <><label htmlFor="name">Full name</label><input id="name" name="name" required placeholder="Your full name" /><label htmlFor="email">Email address</label><input id="email" name="email" type="email" required placeholder="you@example.com" /><label htmlFor="phone">Phone number</label><input id="phone" name="phone" required placeholder="+91 98765 43210" /><label htmlFor="business">Business name</label><input id="business" name="business" required placeholder="Your business name" /><button className="button button-primary full-width" type="submit">Continue to e-KYC <ArrowRight size={16} /></button></> : <><p className="otp-copy">We sent a verification code to your registered phone number. Enter the six-digit demo code to complete simulated e-KYC.</p><label htmlFor="otp">Verification code</label><input id="otp" name="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required placeholder="123456" /><button className="button button-primary full-width" type="submit">Verify and create account <ArrowRight size={16} /></button><button className="button button-quiet full-width" type="button" onClick={() => setStep(1)}>Edit details</button></>}{error && <p className="form-error">{error}</p>}</form><p className="login-footer">Already registered? <Link href="/login">Sign in</Link></p></section></main></div>;
}
